variable "project_name" {}
variable "vpc_id" {}
variable "cmc_role_eks" {}
variable "cmc_role_nodes" {}
variable "private_subnet_1a" {}
variable "private_subnet_1b" {}
variable "public_subnet_1b" {}
variable "public_subnet_1a" {}
variable "cmc-att-amazoneEKSWorkerNodePolicy" {}
variable "cmc-att-amazoneEKSCNIPolicy" {}
variable "mc-att-AmazonEC2ContainerRegistryFullAccess" {}
variable "cmc-att-amazoneEKSClusterPolicy" {}
